### ISSUE TITLE
PNG Export problem

### ISSUE THREAD

**Issue by yosoufe** [tensorflow/tensorboard#370]
I was using tensorboard installed with pip on python 3, everything looks good. very nice PNG export. It was with my PC at my office with a big screen. This the output of it:
![graph-run](https://user-images.githubusercontent.com/7648675/29383648-7a90ff76-82d1-11e7-9c5c-82986e673b37.png)

Now I want to export the almost the same network with my PC at home, the PNG looks rediculously low resolution and distorted. At home I have compiled the tensorflow from source and the version is '1.3.0-rc2'. And I have a very low resolution screen at home
this is the output:

![graph-large_attrs_key _too_large_attrs limit_attr_size 1024 run](https://user-images.githubusercontent.com/7648675/29383637-7491be4e-82d1-11e7-8810-d8b1edaaf0bd.png)

**Comment by wchargin** [comment]
Hi—thanks for reporting. This is known: see #88.

**Comment by wchargin** [comment]
@yosoufe Thanks for pinging us here; I've just fixed this in #371 and will let you know when it merges.

**Comment by wchargin** [comment]
@yosoufe fixed; this should be in our 0.1.3 release.

**Comment by yosoufe** [comment]
@wchargin I have reinstalled tensorflow from the source. Shall I update the tensorboard independently. Because I still get the low resolution PNG export. How should I update it??

**Comment by wchargin** [comment]
@yosoufe: Could you please post the outputs of `pip list`, `which tensorboard`, and `python -c 'import tensorboard.version; print(tensorboard.version.VERSION)'`?

**Comment by yosoufe** [comment]
`pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
appdirs (1.4.3)
apturl (0.5.2)
arrow (0.10.0)
autograd (1.1.11)
backports.weakref (1.0rc1)
beautifulsoup4 (4.4.1)
bidict (0.13.1)
bleach (1.5.0)
blinker (1.3)
Brlapi (0.6.4)
CDApplet (1.0)
CDBashApplet (1.0)
chardet (2.3.0)
checkbox-support (0.22)
click (6.7)
colorama (0.3.9)
command-not-found (0.3)
cryptography (1.2.3)
cycler (0.10.0)
Cython (0.26)
daemonocle (1.0.1)
decorator (4.0.10)
defer (1.0.6)
devscripts (2.16.2ubuntu3)
entrypoints (0.2.2)
feedparser (5.1.3)
future (0.16.0)
guacamole (0.9.2)
h5py (2.7.0)
html5lib (0.9999999)
httplib2 (0.9.1)
idna (2.0)
imageio (1.6)
inotify-simple (1.1.1)
ipykernel (4.6.1)
ipython (6.1.0)
ipython-genutils (0.2.0)
ipywidgets (6.0.0)
jedi (0.10.2)
Jinja2 (2.9.5)
jsonschema (2.6.0)
jupyter (1.0.0)
jupyter-client (5.1.0)
jupyter-console (5.1.0)
jupyter-core (4.3.0)
keyring (10.3.2)
language-selector (0.1)
louis (2.6.4)
lxml (3.5.0)
Magic-file-extensions (0.2)
Mako (1.0.3)
Markdown (2.2.0)
MarkupSafe (0.23)
matplotlib (2.0.0)
mistune (0.7.3)
moviepy (0.2.2.11)
mpmath (0.19)
Nautilus-scripts-manager (2.0)
nbconvert (5.1.1)
nbformat (4.3.0)
nose (1.3.7)
notebook (4.4.1)
numpy (1.13.1)
oauthlib (1.0.3)
onboard (1.2.0)
onedrivesdk (1.1.8)
packaging (16.8)
padme (1.1.1)
pandas (0.19.2)
pandocfilters (1.4.1)
pbr (1.10.0)
pexpect (4.0.1)
pickleshare (0.7.4)
Pillow (3.1.2)
pip (9.0.1)
plainbox (0.25)
portpicker (1.1.1)
prompt-toolkit (1.0.15)
protobuf (3.4.0)
psutil (5.2.2)
ptyprocess (0.5)
py (1.4.33)
py-cpuinfo (3.3.0)
pyasn1 (0.1.9)
pycuda (2016.1.2)
pycups (1.9.73)
pycurl (7.43.0)
Pygments (2.2.0)
pygobject (3.20.0)
PyJWT (1.3.0)
pyparsing (2.1.10)
pytest (3.0.7)
python-apt (1.1.0b1)
python-dateutil (2.6.0)
python-debian (0.1.27)
python-systemd (231)
pytools (2016.2.6)
pytz (2016.10)
pyxdg (0.25)
PyYAML (3.12)
pyzmq (16.0.2)
qtconsole (4.2.1)
reportlab (3.3.0)
requests (2.13.0)
scikit-learn (0.18)
scipy (0.19.1)
screen-resolution-extra (0.0.0)
SecretStorage (2.3.1)
Send2Trash (1.3.0)
sessioninstaller (0.0.0)
setuptools (36.2.7)
simplegeneric (0.8.1)
six (1.10.0)
sklearn (0.0)
ssh-import-id (5.5)
stevedore (1.20.0)
sympy (1.0)
system-service (0.3)
tabulate (0.7.7)
tensorflow (1.3.0)
tensorflow-tensorboard (0.1.2)
terminado (0.6)
testpath (0.3)
Theano (0.8.2)
tornado (4.5.1)
tqdm (4.10.0)
traitlets (4.3.2)
ubuntu-drivers-common (0.0.0)
ufw (0.35)
unattended-upgrades (0.1)
unity-scope-calculator (0.1)
unity-scope-chromiumbookmarks (0.1)
unity-scope-colourlovers (0.1)
unity-scope-devhelp (0.1)
unity-scope-firefoxbookmarks (0.1)
unity-scope-gdrive (0.7)
unity-scope-manpages (0.1)
unity-scope-openclipart (0.1)
unity-scope-texdoc (0.1)
unity-scope-tomboy (0.1)
unity-scope-virtualbox (0.1)
unity-scope-yelp (0.1)
unity-scope-zotero (0.1)
urllib3 (1.13.1)
usb-creator (0.3.0)
virtualenv (15.1.0)
virtualenv-clone (0.2.6)
virtualenvwrapper (4.7.2)
wcwidth (0.1.7)
Werkzeug (0.12.2)
wheel (0.29.0)
widgetsnbextension (2.0.0)
xdiagnose (3.8.4.1)
xkit (0.0.0)
XlsxWriter (0.7.3)
zgitignore (0.7.1)
`

`which tensorboard
/usr/local/bin/tensorboard
`

`python -c 'import tensorboard.version; print(tensorboard.version.VERSION)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named tensorboard.version
`

But:

**Comment by wchargin** [comment]
Please `pip install tensorflow-tensorboard==0.1.4`, and you should be good. (You upgraded your TensorFlow, but are still using the old version 0.1.2 of TensorBoard.)

**Comment by yosoufe** [comment]
worked nicely, Thanks
