### ISSUE TITLE
TensorBoard doesn't work on IOS/IpadOS. Requires apple icons.

### ISSUE THREAD

**Issue by NikitaGordia** [tensorflow/tensorboard#5493]
After starting the server it gives the following result:

W0107 19:43:36.780149 139768956442176 application.py:556] path /apple-touch-icon-precomposed.png not found, sending 404
W0107 19:43:36.798506 139768956442176 application.py:556] path /apple-touch-icon.png not found, sending 404
W0107 19:43:36.832389 139768956442176 application.py:556] path /apple-touch-icon-precomposed.png not found, sending 404
W0107 19:43:36.849392 139768956442176 application.py:556] path /apple-touch-icon.png not found, sending 404
W0107 19:43:36.900132 139768956442176 application.py:556] path /apple-touch-icon-precomposed.png not found, sending 404
W0107 19:43:36.915132 139768956442176 application.py:556] path /apple-touch-icon.png not found, sending 404
W0107 19:43:36.948019 139768956442176 application.py:556] path /apple-touch-icon-precomposed.png not found, sending 404
W0107 19:43:36.965894 139768956442176 application.py:556] path /apple-touch-icon.png not found, sending 404

And in afterwards you can not access tensorboard on apple devices (tested on Iphone 8, iphone 11, ipad 2018). but on android/chome(macos) works great

**Comment by bmd3k** [comment]
Thanks for the additional details. I was able to reproduce the problem on a simulator and that it is fixed by https://github.com/tensorflow/tensorboard/pull/5495. It's the same root cause as https://github.com/tensorflow/tensorboard/issues/5489.

**Comment by NikitaGordia** [comment]
Thank you for your job! Hope to see learning curves of my deep neural networks on Safari :)

**Comment by s-rog** [comment]
This error message about missing icons is still present in 2.18, though tensorboard works fine otherwise.
